# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83588171ebad05b7ca291720f5b543489f66232e49c807cf654dbcd812250a43341ae6d9ebb54712b49186991abe9dbbcc5cd33d8323d36da28122188e15ac83

test:
  secret_key_base: c5505848f0339ece1fc3bdd1f534126226c8d7bfd56639dd5945fb0bf6049f9308d8a45013f25a29a1c1d38081b32beb916a6b96134bbecbc1b43f6529ebc7bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
